# Generated by Django 2.2.5 on 2019-09-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthDayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='姓名')),
                ('birth_day', models.DateField(verbose_name='生日')),
                ('group_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='分组')),
                ('open_id', models.CharField(max_length=255, verbose_name='微信openId')),
                ('is_lunar_calendar', models.IntegerField(choices=[(1, '农历'), (2, '公历')], default=1, verbose_name='历法')),
                ('ctime', models.DateTimeField(auto_now_add=True, verbose_name='姓名')),
                ('utime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
