# Generated by Django 2.2.5 on 2019-10-28 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayrecord',
            name='group_name',
        ),
        migrations.AddField(
            model_name='birthdayrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
