# Generated by Django 2.2.5 on 2019-10-28 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20191028_0658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='birthdayrecord',
            name='open_id',
        ),
    ]
