# Generated by Django 2.2.5 on 2019-11-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_remove_birthdayrecord_open_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdayrecord',
            name='phone_number',
            field=models.CharField(default='', max_length=64, verbose_name='电话号码'),
        ),
    ]
