# Generated by Django 2.2.5 on 2019-10-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.IntegerField(default=100, verbose_name='group id'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_name',
            field=models.CharField(default='support', max_length=128, verbose_name='Group Name'),
        ),
    ]
